export const coachCopy = {
  common: {
    back: 'Back',
    cancel: 'Cancel',
    confirm: 'Confirm',
    notSet: 'Not set',
    bodyweight: 'Bodyweight',
    sets: 'sets',
    reps: 'reps',
    weight: 'Weight',
    secondsShort: 'sec',
    minutes: (value: number) => `${value} min`,
    exercises: (value: number) => `${value} exercises`,
  },
  options: {
    levels: {
      beginner: { label: 'Beginner', desc: 'Just getting started' },
      intermediate: { label: 'Intermediate', desc: 'Training consistently' },
      advanced: { label: 'Advanced', desc: 'Comfortable with intensity' },
    },
    goals: {
      muscle_gain: { label: 'Build muscle', desc: 'Increase muscle size' },
      fat_loss: { label: 'Fat loss', desc: 'Manage body fat and weight' },
      strength: { label: 'Strength', desc: 'Improve main lifts' },
    },
    genders: {
      male: { label: 'Male', desc: 'Helps me tune training volume' },
      female: { label: 'Female', desc: 'Helps me tune training volume' },
      not_specified: { label: 'Skip for now', desc: 'I will use a general plan' },
    },
    categories: {
      warmup: 'Warm-up',
      main: 'Main',
      accessory: 'Accessory',
      finisher: 'Finisher',
      cooldown: 'Cooldown',
    },
    muscleGroups: {
      auto: 'Smart pick',
      legs: 'Legs',
      chest: 'Chest',
      back: 'Back',
      shoulders: 'Shoulders',
      arms: 'Arms',
      full_body: 'Full body',
    },
    adjust: {
      low_energy: 'Lower intensity',
      high_intensity: 'Push harder',
      short_time: 'Only 30 minutes',
      swap: 'Swap selected moves',
      custom: 'Custom adjustment',
    },
  },
  home: {
    records: 'History',
    profile: 'My status',
    start: 'Train today',
    startSub: "I'll guide you",
    hint: 'Reasoning Agent · Multi-signal decision making',
  },
  auth: {
    loginTitle: 'Ready to train today?',
    loginLoading: 'Opening the training room...',
    loginAction: 'Enter training',
    registerLink: 'Create account',
    registerTitle: "Let's set up your account",
    registerSub: 'I will use your training history to make each plan fit you better.',
    registerLoading: 'Preparing your training space...',
    registerAction: 'Create account',
    existingAccount: 'Already have an account?',
    goLogin: 'Log in',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    namePlaceholder: 'Your name',
    passwordPlaceholder: 'At least 6 characters',
    confirmPasswordPlaceholder: 'Type it again',
    passwordMismatch: 'The two passwords do not match',
  },
  onboarding: {
    title: 'Let me get to know you',
    subtitle: 'These details help me make your first workout fit better.',
    gender: 'Your gender',
    experience: 'Your training experience',
    goal: 'Your current goal',
    height: 'Height cm',
    weight: 'Weight kg',
    heightError: 'Please enter a valid height (100-250 cm)',
    weightError: 'Please enter a valid weight (30-300 kg)',
    saving: 'Saving this...',
    action: "All set. Let's train",
  },
  week: {
    title: 'This Week',
    todayTitle: "Today's training",
    todayWorkout: "Today's training",
    pending: 'Unplanned',
    rest: 'Recovery day',
    done: 'Done',
    future: 'Upcoming',
    fallbackWorkout: "today's training",
    cta: "Let's start",
    month: (value: number) => new Date(2026, value - 1, 1).toLocaleString('en-US', { month: 'short' }),
    day: (value: number) => `${value}`,
    dayNames: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    syncError: (message: string) => `I could not sync this yet: ${message}`,
    coachMessages: {
      yesterday: (workout: string, previous: string) => [
        `You completed ${previous} yesterday. Today we focus on ${workout}, keep your form clean, and move one step forward.`,
        `${previous} gave you a good base yesterday. Today is ${workout}. No need to rush; stay steady with each set.`,
        `You already showed up yesterday. Today, ${workout} is ready. Let's ease into it and build the rhythm.`,
      ],
      many: (workout: string, count: number) => [
        `You have finished ${count} sessions this week. Today is ${workout}; keep it focused and make every rep count.`,
        `${count} sessions already this week. Nice rhythm. For ${workout}, quality comes first.`,
        `Your week has momentum. Keep breathing steady and finish ${workout} one set at a time.`,
      ],
      one: (workout: string) => [
        `You already have one session banked this week. Today, finish ${workout} and keep the habit moving.`,
        `The first step is done. Now we connect it with ${workout}; once you start, the body will follow.`,
        `You have one workout in the books. Let's add ${workout} and give the week more direction.`,
      ],
      none: (workout: string) => [
        `Start this week with ${workout}. No need for perfect; just take the first step.`,
        `Let's switch on ${workout} today. Starting is the hardest part.`,
        `It is not too late to start the week now. Finish ${workout} and send your body a clear signal.`,
        `Simple goal for today: enter training and finish ${workout}. I will guide you set by set.`,
      ],
    },
  },
  plan: {
    title: "Today's training",
    loading: "I am checking your recent rhythm and building today's plan.",
    generationFailed: 'This plan did not come through',
    retry: 'Try again',
    duration: (minutes: number) => `Est. ${minutes} min`,
    exercisesCount: (count: number) => `${count} exercises`,
    muscleGroup: 'What should we train today?',
    quickAdjust: 'How should we tune today?',
    selectSwapFirst: 'Select the moves you want to swap, then I will replace them.',
    swapMessage: (names: string[]) => `Only swap these selected exercises: ${names.join(', ')}. Keep the unselected exercises when possible.`,
    thinking: 'I am reworking the exercises...',
    start: 'Start training',
  },
  workout: {
    entering: 'Opening your workout.',
    missingPlan: "I do not have today's plan yet. Let's go back and build it again.",
    unavailable: 'We cannot start this one yet',
    noExercises: 'No exercises available',
    backToPlan: 'Back to plan',
    inProgress: "Let's train together",
    finishedTitle: 'You got this one done',
    summary: (completed: number, skipped: number, minutes: number) =>
      `Completed ${completed} exercises · Skipped ${skipped} · About ${minutes} min`,
    tooHeavyNote: (count: number) => `I noted ${count} exercises that felt heavy so we can adjust later.`,
    saving: 'Saving this...',
    saved: 'I saved it. Nice work getting this session done.',
    save: 'Save this workout',
    home: 'Back home',
    restTitle: 'Take a breath',
    restSubtitle: 'Breathe and sip water',
    nextSet: 'Next set coming up',
    nextExerciseFallback: 'Training',
    setLabel: (current: number, total: number) => `Set ${current} / ${total}`,
    nextSetLabel: (set: number) => `Set ${set}`,
    skipRest: 'I am ready',
    completeSet: 'Set complete',
    tooHeavy: 'Too heavy',
    skipExercise: 'Skip this',
    endWorkout: 'Stop here',
    minSaveError: 'Complete at least 1 exercise before I can save this workout.',
    saveFailed: "This workout did not save. Let's try again.",
  },
  records: {
    title: 'Training History',
    loading: 'Looking through your workouts...',
    errorTitle: 'I could not load history',
    emptyTitle: 'No saved workouts yet',
    emptySubtitle: 'After you finish and save a workout, I will keep it here.',
    detailTitle: 'Workout Detail',
    detailLoading: 'Opening this workout...',
    detailErrorTitle: 'This record will not open right now',
    missing: 'Training record not found',
    summary: (date: string, minutes: number, count: number) => `${date} · ${minutes} min · ${count} exercises`,
  },
  profile: {
    title: 'My Status',
    guestName: 'Not logged in',
  },
  settings: {
    title: 'Settings',
    profileTitle: 'Edit Profile',
    editProfile: 'Edit Profile',
    editProfileSub: 'Experience, goal, height, weight',
    logout: 'Log out',
    logoutSub: 'Return to login',
    level: 'Experience level',
    goal: 'Training goal',
    heightPlaceholder: 'Height cm',
    weightPlaceholder: 'Weight kg',
    saved: 'Profile updated',
    saveLoading: 'Updating...',
    save: 'Save changes',
    chooseLevel: 'Choose experience level',
    chooseGoal: 'Choose training goal',
  },
}

export type CoachCopy = typeof coachCopy

export function useCoachCopy() {
  return coachCopy
}
